language: node_js
node_js:
  - "7.9.0"

cache:
  yarn: true
  directories:
    - node_modules

script:
  - "yarn run lint"
  - "yarn run build-travis"
  - "yarn run release"
  - "./node_modules/.bin/karma start --browsers Firefox --single-run"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3"
