language: node_js
node_js:
  - "12.8.0"

cache:
  yarn: true
  directories:
    - node_modules

services:
  - xvfb

script:
  - "yarn run lint"
  - "yarn run build-travis"
  - "yarn run release"
  - "./node_modules/.bin/karma start --browsers Firefox --single-run"
